spring:
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  resources:
    static-locations: file:src/main/resources/static/
    cache:
      period: 0
  jpa:
    open-in-view: 'false'
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  mail:
    host: smtp.gmail.com
    username: rizalhadiyansah@gmail.com
    properties:
      mail:
        smtp:
          starttls:
            required: 'true'
            enable: 'true'
          connection-timeout: '30000'
          timeout: '30000'
          auth: 'true'
    protocol: smtp
    test-connection: 'false'
    port: '587'
    password: sfsdqzdqbvbcpqfl
    default-encoding: UTF-8
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/restaurant?stringtype=unspecified
    password: root
  messages:
    basename: base
  server:
    port: '8080'
